### PR TITLE
install LNLib

### PR DESCRIPTION
**Pull request by xnaut**

### CODE REVIEW

**Comment by jiayu2019** [comment]
@andre-caldas Would you please take a look ?

**Comment by andre-caldas** [comment]
```tty
andre@clonian:~/hd_extra/repositorios/LNLib$ rm build -rf; mkdir build && cd build
andre@clonian:~/hd_extra/repositorios/LNLib/build$ cmake .. -DCMAKE_INSTALL_PREFIX=~/.local/
-- The C compiler identification is GNU 14.0.1
-- The CXX compiler identification is GNU 14.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- 
-- Configured Eigen 3.4.90
-- 
-- Found Python: /usr/bin/python3 (found version "3.11.9") found components: Interpreter
-- Configuring done (31.1s)
-- Generating done (0.0s)
-- Build files have been written to: /home/andre/hd_extra/repositorios/LNLib/build
andre@clonian:~/hd_extra/repositorios/LNLib/build$ make
[  1%] Building CXX object src/LNLib/CMakeFiles/LNLib.dir/Algorithm/ControlPointsUtils.cpp.o
[  3%] Building CXX object src/LNLib/CMakeFiles/LNLib.dir/Algorithm/Integrator.cpp.o
[  5%] Building CXX object src/LNLib/CMakeFiles/LNLib.dir/Algorithm/Interpolation.cpp.o
[  7%] Building CXX object src/LNLib/CMakeFiles/LNLib.dir/Algorithm/Intersection.cpp.o
[  9%] Building CXX object src/LNLib/CMakeFiles/LNLib.dir/Algorithm/KnotVectorUtils.cpp.o
[ 11%] Building CXX object src/LNLib/CMakeFiles/LNLib.dir/Algorithm/Polynomials.cpp.o
[ 13%] Building CXX object src/LNLib/CMakeFiles/LNLib.dir/Algorithm/Projection.cpp.o
[ 15%] Building CXX object src/LNLib/CMakeFiles/LNLib.dir/Algorithm/ValidationUtils.cpp.o
[ 17%] Building CXX object src/LNLib/CMakeFiles/LNLib.dir/Algorithm/Voronoi.cpp.o
[ 19%] Building CXX object src/LNLib/CMakeFiles/LNLib.dir/Geometry/Curve/BezierCurve.cpp.o
[ 21%] Building CXX object src/LNLib/CMakeFiles/LNLib.dir/Geometry/Curve/NurbsCurve.cpp.o
[ 23%] Building CXX object src/LNLib/CMakeFiles/LNLib.dir/Geometry/Surface/NurbsSurface.cpp.o
[ 25%] Building CXX object src/LNLib/CMakeFiles/LNLib.dir/Mathematics/Math/Constants.cpp.o
[ 27%] Building CXX object src/LNLib/CMakeFiles/LNLib.dir/Mathematics/Math/Matrix4d.cpp.o
[ 29%] Building CXX object src/LNLib/CMakeFiles/LNLib.dir/Mathematics/Math/UV.cpp.o
[ 31%] Building CXX object src/LNLib/CMakeFiles/LNLib.dir/Mathematics/Math/XYZ.cpp.o
[ 33%] Building CXX object src/LNLib/CMakeFiles/LNLib.dir/Mathematics/Math/XYZW.cpp.o
[ 35%] Building CXX object src/LNLib/CMakeFiles/LNLib.dir/Mathematics/Utils/MathUtils.cpp.o
In file included from /home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/Core:19,
                 from /home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/Dense:1,
                 from /home/andre/hd_extra/repositorios/LNLib/src/LNLib/Mathematics/Utils/MathUtils.cpp:21:
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Macros.h:709:2: error: #error Eigen requires at least c++14 support.
  709 | #error Eigen requires at least c++14 support.
      |  ^~~~~
In file included from /home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/Core:167:
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:214:37: error: ‘remove_const_t’ is not a member of ‘std’; did you mean ‘remove_const’?
  214 | struct is_void : is_same<void, std::remove_const_t<T>> {};
      |                                     ^~~~~~~~~~~~~~
      |                                     remove_const
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:214:37: error: ‘remove_const_t’ is not a member of ‘std’; did you mean ‘remove_const’?
  214 | struct is_void : is_same<void, std::remove_const_t<T>> {};
      |                                     ^~~~~~~~~~~~~~
      |                                     remove_const
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:214:52: error: template argument 2 is invalid
  214 | struct is_void : is_same<void, std::remove_const_t<T>> {};
      |                                                    ^
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:214:53: error: expected ‘{’ before ‘>’ token
  214 | struct is_void : is_same<void, std::remove_const_t<T>> {};
      |                                                     ^~
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:310:27: error: ‘enable_if_t’ is not a member of ‘std’
  310 | struct array_size<T, std::enable_if_t<((T::SizeAtCompileTime & 0) == 0)>> {
      |                           ^~~~~~~~~~~
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:310:27: note: ‘std::enable_if_t’ is only available from C++14 onwards
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:310:27: error: ‘enable_if_t’ is not a member of ‘std’
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:310:27: note: ‘std::enable_if_t’ is only available from C++14 onwards
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:310:71: error: type/value mismatch at argument 2 in template parameter list for ‘template<class T, class EnableIf> struct Eigen::internal::array_size’
  310 | struct array_size<T, std::enable_if_t<((T::SizeAtCompileTime & 0) == 0)>> {
      |                                                                       ^
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:310:71: note:   expected a type, got ‘(<expression error> < ((T::SizeAtCompileTime & 0) == 0))’
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:310:72: error: expected unqualified-id before ‘>’ token
  310 | struct array_size<T, std::enable_if_t<((T::SizeAtCompileTime & 0) == 0)>> {
      |                                                                        ^~
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:344:17: error: ‘index_list_size’ function uses ‘auto’ type specifier without trailing return type
  344 | EIGEN_CONSTEXPR auto index_list_size(const T& x) {
      |                 ^~~~
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:344:17: note: deduced return type only available with ‘-std=c++14’ or ‘-std=gnu++14’
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h: In function ‘constexpr auto Eigen::internal::index_list_size(const T&)’:
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:345:18: error: ‘common_type_t’ in namespace ‘std’ does not name a template type; did you mean ‘common_type’?
  345 |   using R = std::common_type_t<std::ptrdiff_t, std::make_signed_t<decltype(x.size())>>;
      |                  ^~~~~~~~~~~~~
      |                  common_type
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:346:22: error: ‘R’ does not name a type
  346 |   return static_cast<R>(x.size());
      |                      ^
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h: At global scope:
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:403:23: error: ‘integer_sequence’ is not a member of ‘std’
  403 |     std::is_same<std::integer_sequence<bool, values..., true>, std::integer_sequence<bool, true, values...>>;
      |                       ^~~~~~~~~~~~~~~~
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:403:23: note: ‘std::integer_sequence’ is only available from C++14 onwards
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:403:23: error: ‘integer_sequence’ is not a member of ‘std’
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:403:23: note: ‘std::integer_sequence’ is only available from C++14 onwards
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:403:61: error: wrong number of template arguments (1, should be 2)
  403 |     std::is_same<std::integer_sequence<bool, values..., true>, std::integer_sequence<bool, true, values...>>;
      |                                                             ^
In file included from /usr/include/c++/14/bits/stl_pair.h:60,
                 from /usr/include/c++/14/bits/stl_algobase.h:64,
                 from /usr/include/c++/14/vector:62,
                 from /home/andre/hd_extra/repositorios/LNLib/src/LNLib/include/Constants.h:14,
                 from /home/andre/hd_extra/repositorios/LNLib/src/LNLib/include/MathUtils.h:14,
                 from /home/andre/hd_extra/repositorios/LNLib/src/LNLib/Mathematics/Utils/MathUtils.cpp:19:
/usr/include/c++/14/type_traits:780:12: note: provided for ‘template<class, class> struct std::is_same’
  780 |     struct is_same;
      |            ^~~~~~~
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:407:68: error: ‘integer_sequence’ is not a member of ‘std’
  407 | using reduce_any = std::integral_constant<bool, !std::is_same<std::integer_sequence<bool, values..., false>,
      |                                                                    ^~~~~~~~~~~~~~~~
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:407:68: note: ‘std::integer_sequence’ is only available from C++14 onwards
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:407:68: error: ‘integer_sequence’ is not a member of ‘std’
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:407:68: note: ‘std::integer_sequence’ is only available from C++14 onwards
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:407:107: error: wrong number of template arguments (1, should be 2)
  407 | using reduce_any = std::integral_constant<bool, !std::is_same<std::integer_sequence<bool, values..., false>,
      |                                                                                                           ^
/usr/include/c++/14/type_traits:780:12: note: provided for ‘template<class, class> struct std::is_same’
  780 |     struct is_same;
      |            ^~~~~~~
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:408:68: error: ‘integer_sequence’ is not a member of ‘std’
  408 |                                                               std::integer_sequence<bool, false, values...>>::value>;
      |                                                                    ^~~~~~~~~~~~~~~~
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:408:68: note: ‘std::integer_sequence’ is only available from C++14 onwards
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:408:68: error: ‘integer_sequence’ is not a member of ‘std’
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:408:68: note: ‘std::integer_sequence’ is only available from C++14 onwards
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:408:107: error: wrong number of template arguments (3, should be 2)
  408 |                                                        std::integer_sequence<bool, false, values...>>::value>;
      |                                                                                                    ^~

/usr/include/c++/14/type_traits:87:12: note: provided for ‘template<class _Tp, _Tp __v> struct std::integral_constant’
   87 |     struct integral_constant
      |            ^~~~~~~~~~~~~~~~~
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:434:46: error: ‘std::enable_if_t’ has not been declared
  434 |   static meta_yes testFunctor(C const*, std::enable_if_t<(sizeof(return_ptr<C>()->operator()()) > 0)>* = 0);
      |                                              ^~~~~~~~~~~
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:434:57: error: expected ‘,’ or ‘...’ before ‘<’ token
  434 |   static meta_yes testFunctor(C const*, std::enable_if_t<(sizeof(return_ptr<C>()->operator()()) > 0)>* = 0);
      |                                                         ^
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:443:46: error: ‘std::enable_if_t’ has not been declared
  443 |   static meta_yes testFunctor(C const*, std::enable_if_t<(sizeof(return_ptr<C>()->operator()(IndexType(0))) > 0)>* = 0);
      |                                              ^~~~~~~~~~~
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:443:57: error: expected ‘,’ or ‘...’ before ‘<’ token
  443 |   static meta_yes testFunctor(C const*, std::enable_if_t<(sizeof(return_ptr<C>()->operator()(IndexType(0))) > 0)>* = 0);
      |                                                         ^
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:453:22: error: ‘std::enable_if_t’ has not been declared
  453 |       C const*, std::enable_if_t<(sizeof(return_ptr<C>()->operator()(IndexType(0), IndexType(0))) > 0)>* = 0);
      |                      ^~~~~~~~~~~
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:453:33: error: expected ‘,’ or ‘...’ before ‘<’ token
  453 |       C const*, std::enable_if_t<(sizeof(return_ptr<C>()->operator()(IndexType(0), IndexType(0))) > 0)>* = 0);
      |                                 ^
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/Meta.h:639:16: warning: variable templates only available with ‘-std=c++14’ or ‘-std=gnu++14’ [-Wc++14-extensions]
  639 | constexpr bool is_int_or_enum_v = std::is_enum<A>::value || std::is_integral<A>::value;
      |                ^~~~~~~~~~~~~~~~
In file included from /home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/Core:169:
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/ForwardDeclarations.h:163:29: error: ‘conditional_t’ in namespace ‘std’ does not name a template type; did you mean ‘conditional’?
  163 |               typename std::conditional_t<PlainObjectType::IsVectorAtCompileTime, InnerStride<1>, OuterStride<>>>
      |                             ^~~~~~~~~~~~~
      |                             conditional
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/ForwardDeclarations.h:163:42: error: expected ‘>’ before ‘<’ token
  163 |               typename std::conditional_t<PlainObjectType::IsVectorAtCompileTime, InnerStride<1>, OuterStride<>>>
      |                                          ^
In file included from /home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/Core:171:
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h:146:16: error: ‘conditional_t’ in namespace ‘std’ does not name a template type; did you mean ‘conditional’?
  146 |   typedef std::conditional_t<(sizeof(I1) < sizeof(I2)), I2, I1> type;
      |                ^~~~~~~~~~~~~
      |                conditional
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h: In function ‘constexpr int Eigen::internal::compute_default_alignment_helper(int, int)’:
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h:268:1: error: body of ‘constexpr’ function ‘constexpr int Eigen::internal::compute_default_alignment_helper(int, int)’ not a return-statement
  268 | }
      | ^
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h: In function ‘constexpr unsigned int Eigen::internal::compute_matrix_flags(int)’:
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h:313:1: error: body of ‘constexpr’ function ‘constexpr unsigned int Eigen::internal::compute_matrix_flags(int)’ not a return-statement
  313 | }
      | ^
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h: In function ‘constexpr int Eigen::internal::size_at_compile_time(int, int)’:
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h:319:1: error: body of ‘constexpr’ function ‘constexpr int Eigen::internal::size_at_compile_time(int, int)’ not a return-statement
  319 | }
      | ^
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h: At global scope:
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h:449:16: error: ‘conditional_t’ in namespace ‘std’ does not name a template type; did you mean ‘conditional’?
  449 |   typedef std::conditional_t<bool(traits<T>::Flags& NestByRefBit), T const&, const T> type;
      |                ^~~~~~~~~~~~~
      |                conditional
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h:451:16: error: ‘conditional_t’ in namespace ‘std’ does not name a template type; did you mean ‘conditional’?
  451 |   typedef std::conditional_t<bool(traits<T>::Flags& NestByRefBit), T&, T> non_const_type;
      |                ^~~~~~~~~~~~~
      |                conditional
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h:457:16: error: ‘conditional_t’ in namespace ‘std’ does not name a template type; did you mean ‘conditional’?
  457 |   typedef std::conditional_t<bool(internal::is_const<T1>::value), add_const_on_value_type_t<T2>, T2> type;
      |                ^~~~~~~~~~~~~
      |                conditional
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h:491:16: error: ‘conditional_t’ in namespace ‘std’ does not name a template type; did you mean ‘conditional’?
  491 |   typedef std::conditional_t<Evaluate, PlainObject, typename ref_selector<T>::type> type;
      |                ^~~~~~~~~~~~~
      |                conditional
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h:529:16: error: ‘conditional_t’ in namespace ‘std’ does not name a template type; did you mean ‘conditional’?
  529 |   typedef std::conditional_t<is_same<CurrentScalarType, NewScalarType>::value, const XprType&, CastType> type;
      |                ^~~~~~~~~~~~~
      |                conditional
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h:708:16: error: ‘conditional_t’ in namespace ‘std’ does not name a template type; did you mean ‘conditional’?
  708 |   typedef std::conditional_t<is_same<typename traits<ExpressionType>::XprKind, MatrixXpr>::value, MatrixRowType,
      |                ^~~~~~~~~~~~~
      |                conditional
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h:722:16: error: ‘conditional_t’ in namespace ‘std’ does not name a template type; did you mean ‘conditional’?
  722 |   typedef std::conditional_t<is_same<typename traits<ExpressionType>::XprKind, MatrixXpr>::value, MatrixColType,
      |                ^~~~~~~~~~~~~
      |                conditional
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h:737:16: error: ‘conditional_t’ in namespace ‘std’ does not name a template type; did you mean ‘conditional’?
  737 |   typedef std::conditional_t<is_same<typename traits<ExpressionType>::XprKind, MatrixXpr>::value, MatrixDiagType,
      |                ^~~~~~~~~~~~~
      |                conditional
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h:756:18: error: ISO C++ forbids declaration of ‘type name’ with no type [-fpermissive]
  756 |       const std::conditional_t<is_same<typename traits<Expr>::XprKind, MatrixXpr>::value, matrix_type, array_type>>
      |                  ^~~~~~~~~~~~~
/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h:756:114: error: template argument 2 is invalid
  756 |  const std::conditional_t<is_same<typename traits<Expr>::XprKind, MatrixXpr>::value, matrix_type, array_type>>
      |                                                                                                             ^~

/home/andre/hd_extra/repositorios/LNLib/build/_deps/eigen-src/Eigen/src/Core/util/XprHelper.h:812:43: error: ‘std::enable_if_t’ has not been declared
  812 |                                      std::enable_if_t<possibly_same_dense<T1, T2>::value>* = 0) {
      |                                           ^~~~~~~~~~~
```

**Comment by andre-caldas** [comment]
Do we really need `C++11`? Eigen3 demands `C++17`.

Mine is giving Eigen3 compilation error because it says Eigen demands C++17.

So, maybe `CMakeLists.txt` could be changed to `C++17`. In my projects, I use `C++26`, though. :-)

**Comment by BIMCoderLiang** [comment]
From：https://eigen.tuxfamily.org/index.php?title=Main_Page

”Eigen has good compiler support as we run our test suite against many compilers to guarantee reliability and work around any compiler bugs. Eigen up to version 3.4 is standard C++03 and maintains reasonable compilation times. Versions following 3.4 will be C++14.“

consider raise C++ standard version @xnaut

**Pull request merged**
